# Generated by Django 2.2.7 on 2019-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscription_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_text',
            field=models.TextField(blank=True, verbose_name='Текст публикации'),
        ),
    ]
