# Generated by Django 2.2.7 on 2019-11-27 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Publication'),
        ),
    ]
